# ============================================================
# Logging
# ============================================================

# Log levels
# DEBUG, INFO, WARNING, ERROR, CRITICAL
[logging]
[logging.console]
enabled = true               # currently not possible to disable
level = "DEBUG"
dependency_level = "WARNING"

[logging.file]
enabled = true               # currently not possible to disable
level = "DEBUG"
dependency_level = "WARNING"
rotation = "midnight"        # D: Daily, H: Hourly, M: every minute, S: every second, midnight: at midnight
retain_days = 14             # for how many days the logs should be kept
utc_time = false             # true: UTC time, false: local time

# ============================================================
# Video fetching
# ============================================================
[video_fetching]
rss_bozo_level = "permissive" # permissive (log warning), strict (fail on bozo error), ignore (fully ignore bozo), debug (log bozo exception)

# ============================================================
# AI
# ============================================================

[ai]
host = "http://localhost:11434"
default_model = "qwen3.5:9b"
validation_model = "qwen3.5:9b"
summary_model = "qwen3.5:9b"

# how often AI can run and fail to output the requested JSON
# for smaller local AI models, it is usually 2-3 times
max_allowed_json_output_runs = 3


# ============================================================
# Video processing
# ============================================================
[video_processing]
# how often a video can fail in total before it gets marked as FAILED and gets abandoned
# use vidsift videos list --status failed to list all the failed videos
max_retry_attempts = 1

# How recent videos should be.
# The RSS feeds can contain month or even year old videos that may not be wanted
# This limits the newly processed videos to the upload date between today and today - the value
# This is especially useful when just having installed vidsift to set it low to not get videos that may
# have already been watched
# It does NOT affect interrupted or failed videos, only new ones
days_uploaded_before = 7

# how much seconds vidsift should sleep after having processed one video at minimum, (min_vid_delay)
# then how much of random secods will be added (between 0 and random_vid_delay)

# int (< 30)
min_vid_delay = 300 # 5 minutes
# int(< 10)
random_vid_delay = 240 # 4 minutes

[video_processing.yt_dlp]
# all of these settings are passed to yt-dlp, so you can use any yt-dlp setting here
max_retries = 10
sleep_requests = 10                 # seconds
cookies_from_browser = "firefox"    # brave, chrome, chromium, edge, firefox, opera,  safari,  vivaldi,  whale
quiet = true                        # wether yt-dlp should be quiet or not, if false, yt-dlp will print a lot of output to the console
merge_output_format = "mkv"         # output format for merged video and audio
format = "bestvideo+bestaudio/best"

# ============================================================
# Validation
# ============================================================

[validation]
enabled = true

# how many chars should roughly be in one transcript chunk
# the amount of chars getting to the AI are a bit more than 5 x transcript_chunk_char_size
transcript_chunk_char_size = 500 # (<100), int


# ============================================================
# Validation - Pre Validation
# ============================================================

[validation.pre_validation.max_allowed] # (0-1), float
title_punctuation_ratio = 0.07   # how many punctuations (.?!) can be in the title to pass relative to the total char amount of the title
title_uppercase_ratio = 0.4      # how many uppercase can chars there can be relative to the total char amount
title_emoji_ratio = 0.15
title_clickbait_ratio = 0.15
transcript_clickbait_ratio = 0.1

[validation.pre_validation.weak]
title_uppercase_ratio = 0.2
title_emoji_ratio = 0.03
title_punctuation_ratio = 0.04
title_clickbait_ratio = 0.05
transcript_clickbait_ratio = 0.02

[validation.pre_validation.weights] # (0-10), float
title_uppercase_weight = 1.0
title_emoji_weight = 1.0
title_punctuation_weight = 0.5
title_clickbait_weight = 1.5
transcript_clickbait_weight = 2.5


# ============================================================
# Summarization
# ============================================================

[summarization]
enabled = true
char_chunk_size = 10000
output_dir = "/home/user/Documents/vidsift/"


# ============================================================
# Downloads
# ============================================================

[downloads]
enabled = true
output_dir = "/home/user/Videos/.vidsift/"


# ============================================================
# Channels
# ============================================================

[[channels]]
id = "UC9x0AN7BWHpCDHSm9NiJFJQ"
name = "NetworkChuck"
action = "validate"

[[channels]]
id = "UCo71RUe6DX4w-Vd47rFLXPg"
name = "typecraft_dev"
action = "download"

[[channels]]
id = "UC4JX40jDee_tINbkjycV4Sg"
name = "TechWithTim"
action = "summarize"
