from typing import Protocol


class VidsiftService(Protocol):
    def install_service(self) -> None:
        ...
    def uninstall_service(self) -> None:
        ...
    def start_service(self) -> None:
        ...
    def stop_service(self) -> None:
        ...
    def restart_service(self) -> None:
        ...
    def get_status(self) -> str | None:
        ...
