from typing import Protocol


class VidsiftService(Protocol):
    def install_service(self) -> None:
        ...
    def uninstall_service(self) -> None:
        ...
    def atart_service(self) -> None:
        ...
    def stop_service(self) -> None:
        ...
