
CLICKBAIT_TITLE_PHRASES = [
    "you won't believe",
    "this changes everything",
    "gone wrong",
    "i can't believe",
    "the truth about",
    "what happens next",
    "watch until the end",
    "do not try this",
    "before it's deleted",
    "they don't want you to know",
    "exposed",
    "shocking",
    "insane",
    "unbelievable",
    "secret revealed",
    "finally revealed",
    "this is why",
    "nobody talks about",
    "the real reason",
    "i tried it so you don't have to",
    "big mistake",
    "you've been doing it wrong",
    "life changing",
    "viral",
    "must watch",
    "you need to see this",
    "proof",
    "caught on camera",
    "top secret",
    "warning",
    "don't miss this",
    "everything you need to know",
    "this will blow your mind",
    "they lied to you",
    "number one trick",
    "hack",
    "instantly",
    "overnight",
    "easy money",
    "free",
    "100%",
    "guaranteed",
    "the end of",
    "is over",
    "breaking news",
    "massive update",
    "it actually works",
    "you are being fooled",
    "the internet is freaking out",
    "everyone is talking about this",
    "!!",
]

CLICKBAIT_TRANSCRIPT_PHRASES = [
    "make sure to watch until the end",
    "you won't believe what happened",
    "before we continue",
    "smash that like button",
    "hit subscribe",
    "turn on notifications",
    "this is crazy",
    "this changes everything",
    "nobody expected this",
    "i was shocked",
    "this blew my mind",
    "stay tuned",
    "you need to see this",
    "don't skip",
    "it gets worse",
    "it gets even crazier",
    "wait for it",
    "you won't regret it",
    "trust me",
    "this is insane",
    "i couldn't believe it",
    "watch this",
    "here's the secret",
    "the truth is",
    "they don't want you to know this",
    "almost nobody knows this",
    "this one trick",
    "this simple hack",
    "this changes the game",
    "i'll explain everything",
    "the answer will surprise you",
    "what happened next shocked me",
    "keep watching",
    "this is not a joke",
    "you have to hear this",
    "this went viral",
    "people are freaking out",
    "everyone is talking about it",
    "this is huge",
    "this is massive",
    "don't make this mistake",
    "most people fail because",
    "i tested this so you don't have to",
    "this could happen to you",
    "you are doing this wrong",
    "warning",
    "urgent",
    "limited time",
    "act now",
]
